[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
sira_on_solana = "B3WE5AtVbdsAoC2iBjuz8wSBixi8njcJBRVxPW9HcQxX"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/mateo/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
